# Generated by Django 5.0.1 on 2024-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_note_twitter_note_wallet_alter_image_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_wl',
            field=models.BooleanField(default=False),
        ),
    ]
