# Generated by Django 5.0.1 on 2024-01-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_note_is_wl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
