# Generated by Django 5.0.1 on 2024-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_note_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='only_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
