# Generated by Django 5.0.1 on 2024-03-25 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_captcha_sentcaptcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentcaptcha',
            name='uid',
            field=models.CharField(default=uuid.UUID('78396daf-5ba2-4db9-98de-516450691157'), max_length=255, null=True),
        ),
    ]
