# Generated by Django 5.0.1 on 2024-03-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_vote_alter_sentcaptcha_uid_voteteam_voteteamuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteteamuser',
            name='vote',
        ),
        migrations.AddField(
            model_name='voteteamuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.voteteam'),
        ),
    ]
