# Generated by Django 5.0.3 on 2024-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_voteteam_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='only_one_team',
            field=models.BooleanField(default=False),
        ),
    ]
