# Generated by Django 5.0.3 on 2024-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_vote_only_one_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coins', models.IntegerField(default=0, null=True)),
                ('total_tx_vol', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
