# Generated by Django 5.0.3 on 2024-03-30 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteteam',
            options={'ordering': ['order_num']},
        ),
        migrations.AddField(
            model_name='voteteamuser',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.vote'),
        ),
    ]
