# Generated by Django 5.0.3 on 2024-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='mint')),
            ],
        ),
        migrations.CreateModel(
            name='MintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('wl', models.BooleanField(default=False)),
                ('wl1', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
