# Generated by Django 5.0.3 on 2024-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_mintimage_mintsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintsettings',
            name='show_in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
