# Generated by Django 5.0.3 on 2024-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_mintsettings_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintsettings',
            name='sold',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
