# Generated by Django 5.0.3 on 2024-05-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_mintsettings_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteteam',
            name='show_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voteteamuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='data.voteteam'),
        ),
    ]
