# Generated by Django 5.0.3 on 2024-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_voteteam_show_users_alter_voteteamuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintsettings',
            name='time_left',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
