# Generated by Django 5.0.1 on 2024-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
