# Generated by Django 5.0.1 on 2024-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_passwordform_alter_code_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='use_number',
            field=models.IntegerField(default=0),
        ),
    ]
