# Generated by Django 5.0.1 on 2024-03-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_code_use_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fk_wl_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fk_wl_2',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
