# Generated by Django 5.0.1 on 2024-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_claim',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='errors',
            field=models.IntegerField(default=0),
        ),
    ]
