# Generated by Django 5.0.3 on 2024-03-29 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_transaction_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='user uid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='user uid'),
        ),
        migrations.CreateModel(
            name='ClaimHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
