# Generated by Django 5.0.3 on 2024-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_transaction_uid_alter_user_uid_claimhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='uid'),
        ),
    ]
