# Generated by Django 5.0.3 on 2024-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_transaction_options_alter_transaction_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('wl', models.BooleanField(blank=True, default=False)),
                ('wl1', models.BooleanField(blank=True, default=False)),
                ('wl2', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
