# Generated by Django 5.0.3 on 2024-04-06 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='usr')),
                ('claim_add', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoinUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='usr')),
                ('limit_add', models.IntegerField(default=0, null=True)),
                ('click_add', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='claims',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='UserClaimUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_upgrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.claimupgrade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_upgrades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoinsUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_upgrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.coinupgrade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_upgrades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
