# Generated by Django 5.0.3 on 2024-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_claimupgrade_coinupgrade_user_claims_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='claims',
            field=models.IntegerField(default=3),
        ),
    ]
