# Generated by Django 5.0.3 on 2024-04-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_mint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mint',
            name='send_wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
