# Generated by Django 5.0.3 on 2024-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_mint_send_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mint',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
